name: Java CI with Maven
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
publish jobs:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - uses: action/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir stagin && cp target/*.jar staging
      with:
        name: package
        path: staging
